Feature/meteor 1.6 (#406)
* initial upgrade to meteor 1.6 and node 8.8.1

* bash script updates for portability https://en.wikipedia.org/wiki/Shebang_%28Unix%29#Portability

* trying to fix git error:

error: Server does not allow request for unadvertised object 7f9fad6ff1bb2a5d76ce9b76f16158e4539112bd
Fetched in submodule path 'app/packages/flow-router', but it did not contain 7f9fad6ff1bb2a5d76ce9b76f16158e4539112bd. Direct fetching of that commit failed.

git submodule update --init returned exit code 1

Action failed: git submodule update --init

* still trying to fix submodule update error

* grab node_cache logs for build errors

* switched to more modern packages per suggestions on github

* print environment when running CI

* more environment variables

* print OS version

* added meteor version

* install meteor before printing environment

* added which node

* watch polling

* updated meteor run command